version: 2

sphinx:
    configuration: docs/conf.py

formats: []

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"
    jobs:
        post_create_environment:
            - pip install poetry
            - poetry config virtualenvs.create false
        post_install:
            - poetry install --with docs

submodules:
    include: all
