version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    commands:
        - asdf plugin add uv
        - asdf install uv latest
        - asdf global uv latest
        - uv venv
        - uv pip install .[docs]

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false

submodules:
    include: all
