version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
      - uv pip install .[doc] leidenalg
    build:
      html:
        - uv run sphinx-build -T -W -b html docs $READTHEDOCS_OUTPUT/html

submodules:
    include: all
