codecov:
  require_ci_to_pass: false

comment: false

coverage:
    status:
        project:
            default:
                target: 1 # always succeed
        patch:
            default:
                enabled: no
    ignore:
        - "tests/"
github_checks:
    annotations: false
