codecov:
  require_ci_to_pass: no

comment: false

coverage:
    status:
        project:
            default:
                # Require 1% coverage, i.e., always succeed
                target: 1
        patch:
            default:
                enabled: no
    ignore:
        - "tests/"
github_checks:
    annotations: false
