repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.7
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix, --unsafe-fixes]
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.0
      hooks:
          - id: prettier
