from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence


@dataclass(frozen=True)
class ComorbidityIndex:
    """ICD-10 code prefixes of every comorbidity category, weights of the category per weighting scheme, and (milder, more severe) category pairs."""

    codes: Mapping[str, tuple[str, ...]]
    weights: Mapping[str, Mapping[str, int]]
    hierarchy: Sequence[tuple[str, str]]


def _span(first: str, last: str) -> tuple[str, ...]:
    """Code prefixes from `first` to `last`, which only differ in their trailing digits."""
    width = next(i for i, (a, b) in enumerate(zip(first, last, strict=True)) if a != b)
    return tuple(f"{first[:width]}{n:0{len(first) - width}d}" for n in range(int(first[width:]), int(last[width:]) + 1))


_MALIGNANCY = (
    *_span("C00", "C26"),
    *_span("C30", "C34"),
    *_span("C37", "C41"),
    "C43",
    *_span("C45", "C58"),
    *_span("C60", "C76"),
)
_METASTASIS = _span("C77", "C80")
_CONGESTIVE_HEART_FAILURE = (
    "I099",
    "I110",
    "I130",
    "I132",
    "I255",
    "I420",
    *_span("I425", "I429"),
    "I43",
    "I50",
    "P290",
)
_PERIPHERAL_VASCULAR = (
    "I70",
    "I71",
    "I731",
    "I738",
    "I739",
    "I771",
    "I790",
    "I792",
    "K551",
    "K558",
    "K559",
    "Z958",
    "Z959",
)
_CHRONIC_PULMONARY = ("I278", "I279", *_span("J40", "J47"), *_span("J60", "J67"), "J684", "J701", "J703")
_PARALYSIS = ("G041", "G114", "G801", "G802", "G81", "G82", *_span("G830", "G834"), "G839")
_AIDS_HIV = ("B20", "B21", "B22", "B24")
_DIABETES = ("E10", "E11", "E12", "E13", "E14")

CHARLSON = ComorbidityIndex(
    codes={
        "myocardial_infarction": ("I21", "I22", "I252"),
        "congestive_heart_failure": _CONGESTIVE_HEART_FAILURE,
        "peripheral_vascular_disease": _PERIPHERAL_VASCULAR,
        "cerebrovascular_disease": ("G45", "G46", "H340", *_span("I60", "I69")),
        "dementia": (*_span("F00", "F03"), "F051", "G30", "G311"),
        "chronic_pulmonary_disease": _CHRONIC_PULMONARY,
        "rheumatic_disease": ("M05", "M06", "M315", "M32", "M33", "M34", "M351", "M353", "M360"),
        "peptic_ulcer_disease": _span("K25", "K28"),
        "mild_liver_disease": (
            "B18",
            *_span("K700", "K703"),
            "K709",
            *_span("K713", "K715"),
            "K717",
            "K73",
            "K74",
            "K760",
            *_span("K762", "K764"),
            "K768",
            "K769",
            "Z944",
        ),
        "diabetes_uncomplicated": tuple(f"{d}{n}" for d in _DIABETES for n in (0, 1, 6, 8, 9)),
        "diabetes_complicated": tuple(f"{d}{n}" for d in _DIABETES for n in (2, 3, 4, 5, 7)),
        "hemiplegia_paraplegia": _PARALYSIS,
        "renal_disease": (
            "I120",
            "I131",
            *_span("N032", "N037"),
            *_span("N052", "N057"),
            "N18",
            "N19",
            "N250",
            *_span("Z490", "Z492"),
            "Z940",
            "Z992",
        ),
        "malignancy": (*_MALIGNANCY, *_span("C81", "C85"), "C88", *_span("C90", "C97")),
        "moderate_severe_liver_disease": (
            "I850",
            "I859",
            "I864",
            "I982",
            "K704",
            "K711",
            "K721",
            "K729",
            *_span("K765", "K767"),
        ),
        "metastatic_solid_tumor": _METASTASIS,
        "aids_hiv": _AIDS_HIV,
    },
    weights={
        "charlson": {
            "myocardial_infarction": 1,
            "congestive_heart_failure": 1,
            "peripheral_vascular_disease": 1,
            "cerebrovascular_disease": 1,
            "dementia": 1,
            "chronic_pulmonary_disease": 1,
            "rheumatic_disease": 1,
            "peptic_ulcer_disease": 1,
            "mild_liver_disease": 1,
            "diabetes_uncomplicated": 1,
            "diabetes_complicated": 2,
            "hemiplegia_paraplegia": 2,
            "renal_disease": 2,
            "malignancy": 2,
            "moderate_severe_liver_disease": 3,
            "metastatic_solid_tumor": 6,
            "aids_hiv": 6,
        },
        "quan": {
            "myocardial_infarction": 0,
            "congestive_heart_failure": 2,
            "peripheral_vascular_disease": 0,
            "cerebrovascular_disease": 0,
            "dementia": 2,
            "chronic_pulmonary_disease": 1,
            "rheumatic_disease": 1,
            "peptic_ulcer_disease": 0,
            "mild_liver_disease": 2,
            "diabetes_uncomplicated": 0,
            "diabetes_complicated": 1,
            "hemiplegia_paraplegia": 2,
            "renal_disease": 1,
            "malignancy": 2,
            "moderate_severe_liver_disease": 4,
            "metastatic_solid_tumor": 6,
            "aids_hiv": 4,
        },
    },
    hierarchy=(
        ("mild_liver_disease", "moderate_severe_liver_disease"),
        ("diabetes_uncomplicated", "diabetes_complicated"),
        ("malignancy", "metastatic_solid_tumor"),
    ),
)

ELIXHAUSER = ComorbidityIndex(
    codes={
        "congestive_heart_failure": _CONGESTIVE_HEART_FAILURE,
        "cardiac_arrhythmias": (
            *_span("I441", "I443"),
            "I456",
            "I459",
            "I47",
            "I48",
            "I49",
            "R000",
            "R001",
            "R008",
            "T821",
            "Z450",
            "Z950",
        ),
        "valvular_disease": (
            "A520",
            *_span("I05", "I08"),
            "I091",
            "I098",
            *_span("I34", "I39"),
            *_span("Q230", "Q233"),
            *_span("Z952", "Z954"),
        ),
        "pulmonary_circulation_disorders": ("I26", "I27", "I280", "I288", "I289"),
        "peripheral_vascular_disorders": _PERIPHERAL_VASCULAR,
        "hypertension_uncomplicated": ("I10",),
        "hypertension_complicated": ("I11", "I12", "I13", "I15"),
        "paralysis": _PARALYSIS,
        "other_neurological_disorders": (
            *_span("G10", "G13"),
            *_span("G20", "G22"),
            "G254",
            "G255",
            "G312",
            "G318",
            "G319",
            "G32",
            *_span("G35", "G37"),
            "G40",
            "G41",
            "G931",
            "G934",
            "R470",
            "R56",
        ),
        "chronic_pulmonary_disease": _CHRONIC_PULMONARY,
        "diabetes_uncomplicated": tuple(f"{d}{n}" for d in _DIABETES for n in (0, 1, 9)),
        "diabetes_complicated": tuple(f"{d}{n}" for d in _DIABETES for n in range(2, 9)),
        "hypothyroidism": (*_span("E00", "E03"), "E890"),
        "renal_failure": ("I120", "I131", "N18", "N19", "N250", *_span("Z490", "Z492"), "Z940", "Z992"),
        "liver_disease": (
            "B18",
            "I85",
            "I864",
            "I982",
            "K70",
            "K711",
            *_span("K713", "K715"),
            "K717",
            *_span("K72", "K74"),
            "K760",
            *_span("K762", "K769"),
            "Z944",
        ),
        "peptic_ulcer_disease": tuple(f"K2{n}{m}" for n in range(5, 9) for m in (7, 9)),
        "aids_hiv": _AIDS_HIV,
        "lymphoma": (*_span("C81", "C85"), "C88", "C96", "C900", "C902"),
        "metastatic_cancer": _METASTASIS,
        "solid_tumor": (*_MALIGNANCY, "C97"),
        "rheumatoid_arthritis": (
            "L940",
            "L941",
            "L943",
            "M05",
            "M06",
            "M08",
            "M120",
            "M123",
            "M30",
            *_span("M310", "M313"),
            *_span("M32", "M35"),
            "M45",
            "M461",
            "M468",
            "M469",
        ),
        "coagulopathy": (*_span("D65", "D68"), "D691", *_span("D693", "D696")),
        "obesity": ("E66",),
        "weight_loss": (*_span("E40", "E46"), "R634", "R64"),
        "fluid_electrolyte_disorders": ("E222", "E86", "E87"),
        "blood_loss_anemia": ("D500",),
        "deficiency_anemia": ("D508", "D509", *_span("D51", "D53")),
        "alcohol_abuse": ("F10", "E52", "G621", "I426", "K292", "K700", "K703", "K709", "T51", "Z502", "Z714", "Z721"),
        "drug_abuse": (*_span("F11", "F16"), "F18", "F19", "Z715", "Z722"),
        "psychoses": ("F20", *_span("F22", "F25"), "F28", "F29", "F302", "F312", "F315"),
        "depression": ("F204", *_span("F313", "F315"), "F32", "F33", "F341", "F412", "F432"),
    },
    weights={
        "van_walraven": {
            "congestive_heart_failure": 7,
            "cardiac_arrhythmias": 5,
            "valvular_disease": -1,
            "pulmonary_circulation_disorders": 4,
            "peripheral_vascular_disorders": 2,
            "hypertension_uncomplicated": 0,
            "hypertension_complicated": 0,
            "paralysis": 7,
            "other_neurological_disorders": 6,
            "chronic_pulmonary_disease": 3,
            "diabetes_uncomplicated": 0,
            "diabetes_complicated": 0,
            "hypothyroidism": 0,
            "renal_failure": 5,
            "liver_disease": 11,
            "peptic_ulcer_disease": 0,
            "aids_hiv": 0,
            "lymphoma": 9,
            "metastatic_cancer": 12,
            "solid_tumor": 4,
            "rheumatoid_arthritis": 0,
            "coagulopathy": 3,
            "obesity": -4,
            "weight_loss": 6,
            "fluid_electrolyte_disorders": 5,
            "blood_loss_anemia": -2,
            "deficiency_anemia": -2,
            "alcohol_abuse": 0,
            "drug_abuse": -7,
            "psychoses": 0,
            "depression": -3,
        },
    },
    hierarchy=(
        ("hypertension_uncomplicated", "hypertension_complicated"),
        ("diabetes_uncomplicated", "diabetes_complicated"),
        ("solid_tumor", "metastatic_cancer"),
    ),
)

COMORBIDITY_INDICES: Mapping[str, ComorbidityIndex] = {"charlson": CHARLSON, "elixhauser": ELIXHAUSER}
